name: TF Plan & Apply
on:
  push:
    branches:
      - main

env:
  environment: "DEV"

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init -input=false -no-color
      - name: Terraform Plan
        run: |
          terraform plan | tee ${{ github.sha }}-${{env.environment}}-infra-plan
      # - name: Print job summary
      #   uses: sgametrio/terraform-summary-action@main
      #   with:
      #     log-file: "${{ github.sha }}-${{env.environment}}-infra-plan"
      #     # Optional
      #     title: Custom header in the Job summary
      - name:
        run: |
          # sed -i 's/\x1b\[[0-9;]*m//g' -i'' ${{ github.sha }}-${{env.environment}}-infra-plan
          # cat ${{ github.sha }}-${{env.environment}}-infra-plan >> $GITHUB_STEP_SUMMARY
          echo "********************************************" >> $GITHUB_STEP_SUMMARY
          echo '```tf' >> $GITHUB_STEP_SUMMARY
          echo "********************************************" >> $GITHUB_STEP_SUMMARY
          echo "Terraform will perform the following actions:" >> $GITHUB_STEP_SUMMARY
          # cat "${{ github.sha }}-${{env.environment}}-infra-plan" >> $GITHUB_STEP_SUMMARY
          echo "********************************************" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "********************************************" >> $GITHUB_STEP_SUMMARY
