name: TF Plan & Apply
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment_from_input:
        type: choice
        default: "all"
        required: false
        options:
          - DEV
          - QA
      value_test:
        type: string
        default: ""
        required: false

env:
  environment: "DEV"

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ inputs.environment_from_input }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: "deploy__${{ inputs.environment_from_input }}__${{ env.SHORT_SHA }}"
      - name: Create Deployment Tag
        if: steps.check-tag.outputs.exists == 'false'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: "deploy__${{ inputs.deployment_environment }}__${{ env.SHORT_SHA }}"
          tag_prefix: ""
      - name: warning
        if: steps.check-tag.outputs.exists == 'true'
        run: |
          echo "::warning title=WARN::Tag already exits"

      - name: Find Tag
        if: steps.check-tag.outputs.exists == 'true'
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: "deploy__${{ inputs.deployment_environment }}__${{ env.SHORT_SHA }}"
