name: TF Plan & Apply
on:
  push:
    branches:
      - main

env:
  environment: "DEV"

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init -input=false -no-color
      - name: Terraform Plan
        run: terraform plan -out='/tmp/${{ github.sha }}-${{env.environment}}-infra-plan'
      - name: Print job summary
        uses: sgametrio/terraform-summary-action@main
        with:
          log-file: "tmp/${{ github.sha }}-${{env.environment}}-infra-plan"
          # Optional
          title: Custom header in the Job summary
