name: Tag test
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment_from_input:
        type: choice
        required: false
        options:
          - DEV
          - QA

env:
  environment: "DEV"

permissions: write-all

jobs:
  test-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ inputs.environment_from_input }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Get short SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: "deploy__${{ inputs.environment_from_input }}__${{ env.SHORT_SHA }}"
      - name: Create Deployment Tag
        if: steps.check-tag.outputs.exists == 'false'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: "deploy__${{ inputs.environment_from_input }}__${{ env.SHORT_SHA }}"
          tag_prefix: ""
      - name: warning
        if: steps.check-tag.outputs.exists == 'true'
        run: |
          echo "::warning title=WARN::Tag already exits"

      - name: Find Tag
        if: steps.check-tag.outputs.exists == 'true'
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: "deploy__${{ inputs.environment_from_input }}__${{ env.SHORT_SHA }}"
