name: Tag test
on:
  workflow_dispatch:
    inputs:
      commit_id:
        type: string
        required: false

env:
  environment: "DEV"

permissions:
  id-token: write
  contents: write

run-name: "${{ contains(github.head_ref, 'feature/') && 'Feature' || contains(github.head_ref, 'bugfix/') && 'Bugfix' || 'Update' }}: ${{ github.head_ref }} by @${{ github.actor }} -- ${{ inputs.commit_id }}"

jobs:
  test-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ inputs.environment_from_input }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get short SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "NOW1=$(date +'%Y-%m-%dT-%H-%M-%S')" >> $GITHUB_ENV

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: "deploy__DEV__${{ inputs.commit_id }}__${{ env.NOW1 }}"

      - name: Get short NOW SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "NOW2=$(date +'%Y-%m-%dT-%H-%M-%S')" >> $GITHUB_ENV

      - name: Create Deployment Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: "deploy__DEV__${{ inputs.commit_id }}__test__$(date +'%Y-%m-%dT-%H-%M-%S')"
          tag_prefix: ""
      # - name: warning
      #   if: steps.check-tag.outputs.exists == 'true'
      #   run: |
      #     echo "::warning title=WARN::Tag already exits"

      # - name: Find Tag
      #   id: tagger
      #   continue-on-error: true
      #   uses: jimschubert/query-tag-action@v1
      #   with:
      #     include: "deploy__QA__V1.0.0*"
      #     commit-ish: "HEAD"

      # - name: testing
      #   if: ${{ vars.IS_JIRA_CHECK_ENABLED == 'true' && steps.tagger.outcome == 'success'}}
      #   run: |
      #     echo "status : ${{ steps.tagger.outcome}}"
