on:
  pull_request:
    types: [opened]

jobs:
  convert-to-draft:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - run: gh pr ready --undo ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
